In [1]:
import numpy as np

In [3]:
x = np.random.randn(10,2,3)

In [5]:
x.shape[1:]

(2, 3)

In [16]:
x = x.reshape(10,-1)

In [17]:
x = x.reshape(10,*(2,3))

In [18]:
x.shape

(10, 2, 3)

In [19]:
x1 = x.reshape(10,-1)

np.reshape 里面放入元组和可变参数都是可以的

In [22]:
x1.reshape((10,2,3))

array([[[ 1.16355633, -1.14270653, -1.5962603 ],
        [ 1.83545534, -0.41744029,  0.49805692]],

       [[ 0.15898846,  0.87544075,  0.66782293],
        [-0.65711178,  1.07917876,  1.09125561]],

       [[ 1.86427372, -1.44111844,  0.36647511],
        [ 0.1874978 ,  0.35081033,  1.28344651]],

       [[-2.01693729, -0.41178631, -0.32084189],
        [-3.26480627, -1.64008068, -1.17343964]],

       [[ 0.33527016, -0.42687782, -0.77957401],
        [ 0.20729242, -1.17905799,  0.56016239]],

       [[ 0.99278802,  2.10907123, -0.32496645],
        [ 0.2980767 ,  0.06977528,  0.34052132]],

       [[-1.16707949,  1.94728107,  0.55367752],
        [-2.49466206,  0.33595195,  0.46809242]],

       [[ 0.71409052,  2.0399487 , -0.51749603],
        [-0.73017862, -0.0500847 ,  0.89634794]],

       [[-0.58740515, -1.48387298, -0.09575121],
        [-1.23537814, -0.53138809,  0.59052755]],

       [[-0.22722741,  0.38000986,  0.42521672],
        [ 1.73464085, -1.78420609, -0.59320658]]])

In [23]:
x1.reshape(10,2,3)

array([[[ 1.16355633, -1.14270653, -1.5962603 ],
        [ 1.83545534, -0.41744029,  0.49805692]],

       [[ 0.15898846,  0.87544075,  0.66782293],
        [-0.65711178,  1.07917876,  1.09125561]],

       [[ 1.86427372, -1.44111844,  0.36647511],
        [ 0.1874978 ,  0.35081033,  1.28344651]],

       [[-2.01693729, -0.41178631, -0.32084189],
        [-3.26480627, -1.64008068, -1.17343964]],

       [[ 0.33527016, -0.42687782, -0.77957401],
        [ 0.20729242, -1.17905799,  0.56016239]],

       [[ 0.99278802,  2.10907123, -0.32496645],
        [ 0.2980767 ,  0.06977528,  0.34052132]],

       [[-1.16707949,  1.94728107,  0.55367752],
        [-2.49466206,  0.33595195,  0.46809242]],

       [[ 0.71409052,  2.0399487 , -0.51749603],
        [-0.73017862, -0.0500847 ,  0.89634794]],

       [[-0.58740515, -1.48387298, -0.09575121],
        [-1.23537814, -0.53138809,  0.59052755]],

       [[-0.22722741,  0.38000986,  0.42521672],
        [ 1.73464085, -1.78420609, -0.59320658]]])

#### np.newaxis

np.newaxis 为数组增加新的轴

In [24]:
a = np.array([0,1,2])

In [25]:
a[:, np.newaxis]

array([[0],
       [1],
       [2]])

In [27]:
a.reshape(a.shape[0],1)   #与上面等价

array([[0],
       [1],
       [2]])

In [31]:
np.random.randn(5,5)

array([[ 0.19028015,  0.95199976, -1.5040801 , -0.7545782 ,  1.00108311],
       [ 0.02807678,  0.01692596, -1.04645017, -2.08559105,  1.30764376],
       [-1.95533239, -1.23184101,  1.16158469, -1.10277944,  0.44253108],
       [-0.82741087, -1.11251124,  1.34193804, -1.01382451,  0.19353043],
       [ 0.12449098, -0.56386969, -2.00799946,  0.53475839,  0.00598757]])

#### dict.pop()

dict.pop(object,name),如果 dict中没有 object 的话,返回 name,如果有 object的话则返回object的值

In [51]:
dict1= {'a':1,'b':'sgd','c':None,'e':'adam'}
dict1

{'a': 1, 'b': 'sgd', 'c': None, 'e': 'adam'}

In [52]:
a = dict1.pop('a', 1)
a

1

In [53]:
dict1

{'b': 'sgd', 'c': None, 'e': 'adam'}

In [54]:
b = dict1.pop('b', 'sgd')
b

'sgd'

In [55]:
d = dict1.pop('d', 100)
d

100

In [56]:
e = dict1.pop('e', 'sgd')
e

'adam'

#### hasattr, getattr

hasattr用来判断对象是否具有某个属性, getattr 获取对象的某个属性

In [40]:
from cs231n import optim

In [41]:
hasattr(optim, 'sgd')

True

In [57]:
sgd = getattr(optim, 'sgd')
sgd

<function cs231n.optim.sgd(w, dw, config=None)>

In [45]:
li = ['a', 'b']
hasattr(li, 'pop')

True

#### np.hstack

np.hstack() 将一个数组在水平方向展开

In [71]:
y_pred = []
scores1 = np.array([[1,2,3],[2,1,0],[2,3,4]])
y_pred.append(np.argmax(scores1, axis=1))
scores2 = np.array([[1,2,3],[3,1,4],[5,3,4]])
y_pred.append(np.argmax(scores2, axis=1))
y_pred

[array([2, 0, 2]), array([2, 2, 0])]

In [72]:
label = [2,1,2,0,1,3]
y_pred == label

False

In [73]:
y_pred = np.hstack(y_pred)
y_pred

array([2, 0, 2, 2, 2, 0])

In [61]:
a = [[1],[2],[3]]
np.hstack(a)

array([1, 2, 3])

In [79]:
list(range(5,-1,-1))

[5, 4, 3, 2, 1, 0]

一行写不下时可以用 \ 换行

In [83]:
1 + 2 + 3 \
+ 4

10

In [86]:
np.sqrt(0.9*0.1*0.1**2 + 0.1 * 0.05**2)

0.03391164991562635

In [87]:
np.sqrt(0.9*0.1*1 + 0.1 * 0.5**2)

0.33911649915626346