In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3])

In [4]:
print(a)

[1 2 3]


In [5]:
print(type(a))

<class 'numpy.ndarray'>


In [6]:
print(a.shape)

(3,)


In [7]:
b = np.array([[1,2,3],[2,3,4]])

In [8]:
b.shape

(2, 3)

* 两种不同索引

In [9]:
b[0,0]

1

In [10]:
b[0][0]

1

In [11]:
d = np.eye(2)

In [12]:
d

array([[ 1.,  0.],
       [ 0.,  1.]])

In [15]:
e = np.random.random((2,2))

In [16]:
e

array([[ 0.0021315 ,  0.4606487 ],
       [ 0.25536471,  0.68368127]])

In [18]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

* 注意下面索引的不同

In [19]:
col_r1 = a[:,1]
col_r1

array([ 2,  6, 10])

In [20]:
col_r2 = a[:,1:2]
col_r2

array([[ 2],
       [ 6],
       [10]])

In [21]:
col_r3 = a[:,1:3]
col_r3

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

* 寻找异同

In [22]:
a[[0,1,1],[1,0,2]]

array([2, 5, 7])

In [25]:
np.array([a[0,1],a[1,0],a[1,2]])

array([2, 5, 7])

In [26]:
bool_idx = a > 3

In [27]:
bool_idx

array([[False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]], dtype=bool)

In [28]:
a[bool_idx]  # construct rank  1 array

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

In [29]:
x = np.array([[1,2],[3,4]],dtype=np.int64)
x

array([[1, 2],
       [3, 4]], dtype=int64)

和 matlab 中不一样的是，numpy 中的 * 是elementwise,数组乘法需要使用dot

In [31]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
x * y

array([[ 5, 12],
       [21, 32]])

In [32]:
x.dot(y)

array([[19, 22],
       [43, 50]])

In [34]:
np.dot(x,y)

array([[19, 22],
       [43, 50]])

In [40]:
v = np.array([1,2])
w = np.array([4,5])
z = np.array([[1],[2]])

In [45]:
v

array([1, 2])

In [48]:
v.shape

(2,)

In [47]:
np.array([[1,2]])

array([[1, 2]])

* 注意下列异同

In [41]:
v.dot(w)

14

In [42]:
x.dot(v)

array([ 5, 11])

In [43]:
x.dot(z)

array([[ 5],
       [11]])

* 一些数学函数

In [51]:
x

array([[1, 2],
       [3, 4]])

In [49]:
np.sum(x)

10

In [50]:
np.sum(x, axis=0)

array([4, 6])

In [52]:
np.sum(x, axis=1)

array([3, 7])

In [53]:
x.T

array([[1, 3],
       [2, 4]])

* 怎么样用一个小的矩阵来对大矩阵做多次操作？numpy 提供了 broadcasting 机制

In [61]:
x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
y = np.array([1,0,2])

方法一

In [55]:
t = np.empty_like(x)
t

array([[1302372928,        577, 1284151600],
       [       577, 1306563960,        577],
       [1305620240,        577, 1306574896],
       [       577, 1285223968,        577]])

In [59]:
for i in range(4):
    t[i,:] = x[i,:] + y

In [60]:
t

array([[ 2,  2,  5],
       [ 5,  5,  8],
       [ 8,  8, 11],
       [11, 11, 14]])

方法二

In [63]:
tt = np.tile(y, (4,1))
tt

array([[1, 0, 2],
       [1, 0, 2],
       [1, 0, 2],
       [1, 0, 2]])

In [64]:
t = x + y
t

array([[ 2,  2,  5],
       [ 5,  5,  8],
       [ 8,  8, 11],
       [11, 11, 14]])

方法三（broadcasting）

In [65]:
x + y

array([[ 2,  2,  5],
       [ 5,  5,  8],
       [ 8,  8, 11],
       [11, 11, 14]])

broadcasting的原则：
两个数组如果在某一维度上大小是相同的(或者有一个大小是1)，那么就说它们是compatible,就可以 broadcasting

例1

In [67]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([4,5]) # broadcasting (3,2)
x.T + y

array([[ 5,  9],
       [ 6, 10],
       [ 7, 11]])

例2

In [68]:
x = np.array([1,2,3])
y = np.array([4,5])  # y可视作 （1，2）,broadcasting (3,2)
np.reshape(x, (3,1)) * y # x broadcasting (3,2)

array([[ 4,  5],
       [ 8, 10],
       [12, 15]])

例3

In [69]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([1,2,3])
x + y 

array([[2, 4, 6],
       [5, 7, 9]])