In [2]:
import numpy as np

### 下面验证一下 np.concatenate 的用法

In [3]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
x = []
x.append(a)
x.append(b)
x

[array([[1, 2],
        [3, 4]]), array([[5, 6],
        [7, 8]])]

发现不管是列表还是元组都是可以的

In [15]:
x1 = np.concatenate([a,b])
x1

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [17]:
x2 = np.concatenate((a,b))
x2

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [8]:
def my_sum(a, order=0):
    sum = 0
    for i in a:
        sum += i
    return sum

In [9]:
my_sum([1,2,3], 0)

6

In [14]:
my_sum((1,2,3), 0)

6

因为在 for 循环中不仅列表可以循环，元组，字符只要是可迭代的都可以循环

而在下面的my_sum1 函数的定义中，我们是以可变参数来定义的

In [18]:
def my_sum1(*a, order=0):
    sum = 0;
    for i in a:
        sum += i
    return sum

In [19]:
my_sum1(1,2,3)

6

In [20]:
my_sum1([1,2,3])

TypeError: unsupported operand type(s) for +=: 'int' and 'list'

In [21]:
my_sum1(*[1,2,3])

6

In [1]:
def my_sum2(*a, order=0):
    print(a)

In [2]:
my_sum2([1,2,3])

([1, 2, 3],)


可以发现上面放入my_sum2() 中的 列表 [1,2,3] 经由可变参数传入到函数中变成了 ([1,2,3],) 这样的元组。事实上，所有元素经由可变参数传入到函数中，都会被自动组装成元组的形式。

如果用 np.concatenate(a1,a2...)会报错

In [22]:
x3 = np.concatenate(a,b)
x3

TypeError: only integer scalar arrays can be converted to a scalar index

综上 np.concatenate 的调用只能 np.concatenate((a1,a2,...)) 或者 np.concatenate([a1,a2,...]) 

比较异同

In [68]:
a = np.array([1,2,3]) # 可以把它当成列向量
b = np.array([4,5,6,7])
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7])

In [69]:
np.concatenate((a,b), axis=0)

array([1, 2, 3, 4, 5, 6, 7])

In [70]:
np.concatenate((a,b), axis=None)

array([1, 2, 3, 4, 5, 6, 7])

In [79]:
np.concatenate((a,b), axis=1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly

无法对一维数组进行 axis = 1 上的操作，因为一维数组只有一个纵向的维度

In [80]:
a = np.array([1,2,3]) 
b = np.array([4,5,6])
np.concatenate((a,b), axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [71]:
a = np.array([[1,2,3]])
b = np.array([[4,5,6,7]])
np.concatenate((a,b))

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [82]:
a = np.array([[1],[2],[3]])
b = np.array([[4],[5],[7]])
np.concatenate((a,b),axis=1)

array([[1, 4],
       [2, 5],
       [3, 7]])

In [72]:
np.concatenate((a,b), axis=1)

array([[1, 2, 3, 4, 5, 6, 7]])

In [77]:
a = np.array([[1,2],[5,4]])
b = np.array([1,2])
a + b

array([[2, 4],
       [6, 6]])

In [78]:
a = np.array([[1,2],[5,4]])
b = np.array([[1,2]])
a + b

array([[2, 4],
       [6, 6]])

### np.flatnonzero

np.flatnonzero(a) 返回非0数组的下标的平铺形式  

比较：
a.ravel() 返回数组的平铺形式

In [23]:
np.flatnonzero(a)

array([0, 1, 2, 3])

In [25]:
a.ravel()

array([1, 2, 3, 4])

In [27]:
a = np.array([[1,2,3]])
b = np.array([[3,4,5]])
np.sum((a-b)**2)

12

In [28]:
a-b

array([[-2, -2, -2]])

### np.argsort

返回数组从小到大的序号

In [29]:
a = np.array([[3,1,2],[4,7,1]])
np.argsort(a)

array([[1, 2, 0],
       [2, 0, 1]])

### np 中找到出现最多的元素

In [39]:
a = np.array([1,2,3,3,4,4,4,5])
x = np.bincount(a)
x

array([0, 1, 1, 2, 3, 1])

In [40]:
np.argmax(x)

4

### np.sum

In [43]:
a = np.array([[1,2,3],[4,5,6]])
np.sum(a,axis=0)

array([5, 7, 9])

In [45]:
np.sum(a,axis=1)

array([ 6, 15])

In [46]:
np.sum(a)

21

会发现不管axis 是0还是1得出的都是(n,)这样的数组

### 切片

In [47]:
a = np.array([1,2,3])
a.shape

(3,)

In [48]:
[1] + [2]

[1, 2]

In [49]:
[1,2,3][0:1]

[1]

In [50]:
[1,2,3][1:2]

[2]

In [67]:
[1,2,3][0:0]

[]

In [59]:
x1 = []
x2 = []
x1.append(a)
x2.append(a)

比较异同

In [65]:
x1[0:]

[array([1, 2, 3])]

In [66]:
x1[0]

array([1, 2, 3])

In [63]:
x1[0:] + x2[0:]

[array([1, 2, 3]), array([1, 2, 3])]