In [1]:
import numpy as np

这些很多都是来源于 cs231n 中的作业，其中一些 numpy 的高级操作值得整理下来以后参考

### one_hot

In [7]:
idx = np.array([1,2,3,4,2,1])
idx

array([1, 2, 3, 4, 2, 1])

我们想要对 `idx` 进行 one_hot 编码 变成 6x5 的矩阵，可以进行如下操作

In [8]:
x = np.zeros((6,5))
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
x[np.arange(6), idx] = 1
x

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.]])

### 增加维度

In [11]:
x = np.arange(12).reshape(3, 4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

现在 `x` 的维度是 `3x4`，我们想为它增加一个维度让它变成 `3x1x4`，这个有的时候也是有用的，比如说在 `temporal_affine_forward(x, w, b)` 这个函数中的 `x` 的维度是 `NxTxD`，它是可以在多个时间步上一起操作的，但是如果我们想要对一个只有两维的数组，比如输入的 `features` 它的维度是 `NxD` 